### ISSUE TITLE
Rofi themes folder is empty

### ISSUE THREAD

**Issue by tpkee** [linuxmobile/hyprland-dots#1]

**Comment by linuxmobile** [comment]
My mistake! I will fix in few minutes!

**Comment by linuxmobile** [comment]
![image](https://user-images.githubusercontent.com/10554636/180654727-c7ee34c9-5708-425f-881e-76365f76c77f.png)
It' doesnt look empty. idk what r u looking!

**Comment by tpkee** [comment]
Isn't it just a symlink? If i try to open it there's no redirect and after you download it the folder is empty

**Comment by linuxmobile** [comment]
> Isn't it just a symlink to a non-existent folder (at least the version uploaded on here)? If i try to open it there's no redirect and after you download it the folder is empty

Look at the screenshot, scripts are there.

**Comment by tpkee** [comment]
Yeah, the themes folder isn't though...

**Comment by linuxmobile** [comment]
> Yeah, the themes folder isn't though...

You can choose any theme there. Like catpuccin... Wait for readme then..
