### ISSUE TITLE
Audio keybinds not working

### ISSUE THREAD

**Issue by raminsamadi123** [linuxmobile/hyprland-dots#10]
I have a fix for this is in my hyprinstall project (hyprland.conf under #Keybind): https://github.com/raminsamadi123/hyprinstall

**Comment by linuxmobile** [comment]
> I have a fix for this is in my hyprinstall project (hyprland.conf under #Keybind): https://github.com/raminsamadi123/hyprinstall

why didn't you do a fork? Anyway, I don't use that function in my setup. I don't see why add them.

**Comment by raminsamadi123** [comment]
Don’t have much experience with GitHub that is why. But anyways thanks for your amazing project. :)
