### ISSUE TITLE
empty hyprland window being displayed when there is no application open to focus on

### ISSUE THREAD

**Issue by nathish** [linuxmobile/hyprland-dots#14]
How do I hide or disable the center-module in waybar when there is no active window to focus on? Not sure if this is by design. If it is. I'll close the issue. thanks
![image](https://user-images.githubusercontent.com/9541415/218313539-21551f98-febb-45b1-b416-ea6d4665380a.png)

**Comment by linuxmobile** [comment]
> How do I hide or disable the center-module in waybar when there is no active window to focus on? Not sure if this is by design. If it is. I'll close the issue. thanks ![image](https://user-images.githubusercontent.com/9541415/218313539-21551f98-febb-45b1-b416-ea6d4665380a.png)

### For now it is impossible.
