### ISSUE TITLE
Most of the icons do not show in weather

### ISSUE THREAD

**Issue by MrHappy** [linuxmobile/hyprland-dots#15]
When I open the waybar-wttr.py most of the icons are squares.
It is a fresh install.
I have installed the font and ran fc-cache -rv.
I'm sure I'm missing something simple, but don't know what.

**Comment by linuxmobile** [comment]
> When I open the waybar-wttr.py most of the icons are squares. It is a fresh install. I have installed the font and ran fc-cache -rv. I'm sure I'm missing something simple, but don't know what.

you are missing some font.

**Comment by MrHappy** [comment]
Like I said... Something simple 😁
Thanks!
