### ISSUE TITLE
Taking too long to install dependencies

### ISSUE THREAD

**Issue by syylvette** [linuxmobile/hyprland-dots#17]
![Screenshot from 2023-02-20 16-37-32](https://user-images.githubusercontent.com/105774228/220017890-6ebd009f-8afa-4978-a40b-46116581ab6c.png)

How long this takes?

**Comment by its-ag** [comment]
It's usually pretty fast but if you dont wanna compile it (takes time, depending upon your PC's performance) in your machine use the ``hyprland-bin`` package instead of ``hyprland-git``.
```sh
paru -Sy hyprland-bin
```
will install this https://aur.archlinux.org/packages/hyprland-bin

**Comment by syylvette** [comment]
yea it got installed, I was not patient lol

**Comment by syylvette** [comment]
Also how can I get your previous configs of hyprland

**Comment by syylvette** [comment]
Also I am getting this new error, 
```
Run-time dependency gtk-layer-shell-0 found: YES 0.8.0
Run-time dependency systemd found: NO (tried pkgconfig and cmake)

meson.build:125:0: ERROR: Dependency "systemd" not found, tried pkgconfig and cmake

A full log can be found at /home/sylvee/.cache/yay/waybar-hyprland-git/src/build/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: waybar-hyprland-git

```

I am using Artix

**Comment by its-ag** [comment]
Maybe you should try reading the commit history for that.

**Comment by its-ag** [comment]
> waybar-hyprland

```sh
paru -Sy waybar-hyprland
```

Try this: https://aur.archlinux.org/packages/waybar-hyprland

**Comment by its-ag** [comment]
@syylvette You can try this too: https://aur.archlinux.org/packages/waybar-no-systemd

**Comment by syylvette** [comment]
I referred to DMNinja's comment, it worked
[https://aur.archlinux.org/packages/waybar-hyprland-git#comment-898032](url)

**Comment by syylvette** [comment]
@its-ag Getting this error
![IMG_20230220_123659](https://user-images.githubusercontent.com/105774228/220036431-9c9f2f72-0f90-46a0-842d-0271b24ab43c.jpg)

**Comment by its-ag** [comment]
idk what it's in line #41 of you hyprland config, but try to comment out that line and see if it fixes.

**Comment by syylvette** [comment]
hmm, I commented out but I get a blackscreen now and after few seconds it goes back to display manager

**Comment by its-ag** [comment]
https://wiki.hyprland.org/Configuring/Variables/ 
You should try reading this^

**Comment by linuxmobile** [comment]
> Also how can I get your previous configs of hyprland, this ones ![68747470733a2f2f692e696d6775722e636f6d2f553173336a69372e706e67](https://user-images.githubusercontent.com/105774228/220024917-f3123067-d5a7-4d48-afde-02a2de1db139.png)

Download [it](https://github.com/linuxmobile/hyprland-dots/tree/c1d0fab3d673a5b2a225a78a990559f4e114399f) manually

**Comment by linuxmobile** [comment]
### Please, one issue per topic. So that others can find the solution to the problem easier.
