### ISSUE TITLE
Request: workspaces order

### ISSUE THREAD

**Issue by PolGZ** [linuxmobile/hyprland-dots#18]
First of all, sorry to open this an issue on your dot files. I don't know where I should properly open it (official waybar github?) and I don't have a twitter account to message you.

Maybe you can help me achieve this result:

Workspace 10 is shown as the "second" workspace on the waybar, to the right of workspace 1, and to the left of workspace >/= 3, even though it responds correctly to bindings to go/move to workspace 10.

I'm using your waybar config file.

Any suggestions? (the 10th worskspace is the one where I always have my "chat" apps, so it is almost always used. It is very "puzzling" to not have it always to the right of where I'm at, since I use the position of the icons on the bar to easily know what is running and what not already with just a glance at worskpaces and their own icons) .

Last, thank you so so much for these dotfiles and a good documentation on how to use them. I wouldn't be running hyprland without them!

**Comment by linuxmobile** [comment]
There's nothing you can do about it. I'm sorry :(

### Soon I will upload an updated ricing with another bar alternative (ignore volume & mic icons:

![image](https://user-images.githubusercontent.com/10554636/220932947-305b5f11-7240-418a-b369-0150a030b65e.png)
