### ISSUE TITLE
algunas dudas

### ISSUE THREAD

**Issue by juanda3132** [linuxmobile/hyprland-dots#2]
hola, se ve muy bonito, me gusto y estoy intentando instalarlo en mi equipo, pero es primer vez que uso wayland y tengo algunas dudas.
- es necesario instalar el paquete xorg?, o solamente sigo las instrucciones de la publicacion con un artix linux minimal?
- y me preguntaba si me podrias dar una lista mas detallada de dependencias, o mejor dicho si aparte de lo que esta publicado no hiciste o instalaste nada antes.
gracias.

**Comment by linuxmobile** [comment]
> * es necesario instalar el paquete xorg?, o solamente sigo las instrucciones de la publicacion con un artix linux minimal?

_Con respecto a los paquetes de xorg solamente los necesarios cuando instalas wayland._

> * y me preguntaba si me podrias dar una lista mas detallada de dependencias, o mejor dicho si aparte de lo que esta publicado no hiciste o instalaste nada antes.

Con respecto a esto: Actualmente estoy usando waybar, la versión compilada manualmente, ya que es necesario unos parches para que todo funcione. De todas formas no es un manual lo que hice. Sino mis dotfiles, si querés tener instalado algo similar tenés que tener un mínimo de conocimiento!

**Comment by juanda3132** [comment]
amigo, al seguir los pasos, en un artix minimo, cuando ejecuto el comando Hyprland en tty para iniciar me sale un cuadro con este error: 
config error at (~/.config/hypr/hyprland.conf): unknown style
hyprland may not work correctly

dice que el error esta en ese archivo en la linea 26, pero reviso y no encuentro cual puede ser el problema, me podrias ayudar por favor

**Comment by linuxmobile** [comment]
> amigo, al seguir los pasos, en un artix minimo, cuando ejecuto el comando Hyprland en tty para iniciar me sale un cuadro con este error: config error at (~/.config/hypr/hyprland.conf): unknown style hyprland may not work correctly
> 
> dice que el error esta en ese archivo en la linea 26, pero reviso y no encuentro cual puede ser el problema, me podrias ayudar por favor

Eliminá la línea y listo: 

```
animations {
    enabled=1
    animation=windows,1,5,overshot,slide
    animation=borders,1,20,default
    animation=fadein,1,5,default
    animation=workspaces,1,6,overshot,fadein
}
```
