### ISSUE TITLE
New one?

### ISSUE THREAD

**Issue by hoopengo** [linuxmobile/hyprland-dots#20]
How about add `.sh` file that install this one. It will be a nice, because - `curl {link/to/.sh} | sh` and boom! gotcha!

**Comment by linuxmobile** [comment]
> How about add `.sh` file that install this one. It will be a nice, because - `curl {link/to/.sh} | sh` and boom! gotcha!

I'm on holidays right now. I come back and do it

**Comment by radhasec** [comment]
And please try to make .sh for those who don't know hot to config hyprland 

Anyone can install hyprland sucessful after installing minimal arch Linux

**Comment by linuxmobile** [comment]
> And please try to make .sh for those who don't know hot to config hyprland
> 
> Anyone can install hyprland sucessful after installing minimal arch Linux

I write a little guide to install everything. Do you want me to come to your house and install it for you too?
