### ISSUE TITLE
Keyboard layout, dunst and wezterm issue.

### ISSUE THREAD

**Issue by primedust** [linuxmobile/hyprland-dots#25]
hello, I'm a new wm user.
I successfully installed your rice (pretty cool one) thanks to your instructions.
However I was having some problems. 
First my keyboard layout is changed when I enter hyprland. I checked around your configs to see if anything was messing around with that but I couldn't find anything. 
Second, dunst works great when I enter my xfce de , but when I go to hypr it doesn't pop up any notification. Also when I use my keyboard buttons to increase and decrease volume in xfce , dunst and pipewire works perfectly , but not in hyprland. In hypr it does nothing.
Last is that wezterm gives this font error : 
```
Unable to load a font specified by your font=wezterm.font('Cartograph CF',
{weight="Regular", stretch='Normal', style=Normal}) configuration. Fallback(s)
are being used instead, and the terminal may not render as intended. See
https://wezfurlong.org/wezterm/config/fonts.html for more information
```

I believe I might have done something wrong in the installation of fonts but when I think about it , I really haven't. I have installed the fonts, put them to the directory and reloaded font cache. 
Any answer to these issues would be great. Oh, and also, the rice works pretty well even if these issues still held place. They are very minor to be honest.
Thanks for your rice again

**Comment by linuxmobile** [comment]
> First my keyboard layout is changed when I enter hyprland. I checked around your configs to see if anything was messing around with that but I couldn't find anything.

### Read Hyprland WIKI

> Second, dunst works great when I enter my xfce de , but when I go to hypr it doesn't pop up any notification. Also when I use my keyboard buttons to increase and decrease volume in xfce , dunst and pipewire works perfectly , but not in hyprland

Dunst doesn't work automatically to generate any notification, in Hyprland you have to specify the notification, read the Dunst wiki and configure it yourself



> I believe I might have done something wrong in the installation of fonts but when I think about it , I really haven't. I have installed the fonts, put them to the directory and reloaded font cache.
> Any answer to these issues would be great. Oh, and also, the rice works pretty well even if these issues still held place. They are very minor to be honest.
> Thanks for your rice again

Read Instructions:

![](https://i.imgur.com/oTQudGG.png)
