### ISSUE TITLE
waybar completely broken

### ISSUE THREAD

**Issue by Readf0x** [linuxmobile/hyprland-dots#32]
waybar shows up as a tiny square in the bottom right when using the shortcut to restart it, I have to start it manually with the waybar command to make it function, not only that, but even when it is working, I have no icons. I have otf-font-awesome, ttf-font-awesome, and noto-fonts-emoji yet there are still no icons. I have installed every dependency, but not all the apps.

**Comment by Readf0x** [comment]
![image](https://github.com/linuxmobile/hyprland-dots/assets/57838054/9e61c6b9-96b4-4691-89f8-812ca83d7ff1)
![image](https://github.com/linuxmobile/hyprland-dots/assets/57838054/a84fc5df-d426-42a9-9683-7c4013581403)

**Comment by linuxmobile** [comment]
> waybar shows up as a tiny square in the bottom right when using the shortcut to restart it, I have to start it manually with the waybar command to make it function, not only that, but even when it is working, I have no icons. I have otf-font-awesome, ttf-font-awesome, and noto-fonts-emoji yet there are still no icons. I have installed every dependency, but not all the apps.

I can fix the restart keybind. Idk why isnt working, but i will fix. Check the font in style and fix yourself! [Like change font to nerdfont youre usign!

**Comment by Readf0x** [comment]
What font did you make it for? I've spent way too long fixing things today and I really just want to be able to install the missing fonts...

**Comment by linuxmobile** [comment]
> What font did you make it for? I've spent way too long fixing things today and I really just want to be able to install the missing fonts...

Idk im using firecode right now.
