### ISSUE TITLE
1920x1080

### ISSUE THREAD

**Issue by networkmaui** [linuxmobile/hyprland-dots#34]
Hi, I see in hyprland.conf, the resolution is set to auto which is great but things like rofi, brave, seem to be set at a lower resolution. Xrandr for example doesn't give me my native 1920x1080 option.

**Comment by linuxmobile** [comment]
> Hi, I see in hyprland.conf, the resolution is set to auto which is great but things like rofi, brave, seem to be set at a lower resolution. Xrandr for example doesn't give me my native 1920x1080 option.

Not my problem. I'm using 1366x768 monitor.

**Comment by networkmaui** [comment]
Thanks for the wonderful and helpful reply 💕
