### ISSUE TITLE
Icons not appearing in the waybar

### ISSUE THREAD

**Issue by parik-shit** [linuxmobile/hyprland-dots#36]
Some boxes come in place of icons in waybar. Most probably, it is because of font.

**Comment by maclaud** [comment]
you need to install ttf-iosevka-nerd

**Comment by parik-shit** [comment]
> you need to install ttf-iosevka-nerd #28

The font is installed but for some reason waybar is having trouble to understand what font to use.

**Comment by linuxmobile** [comment]
> The font is installed but for some reason waybar is having trouble to understand what font to use.

https://github.com/linuxmobile/hyprland-dots/blob/957ab313173afe41b0864f8d18313f9e4d057253/.config/waybar/style.css#L5
