### ISSUE TITLE
Mouse clicks on the touchpad don't work

### ISSUE THREAD

**Issue by akiko23** [linuxmobile/hyprland-dots#39]
I'v installed it on my laptop and the problem is that if I try to make a mouse click, for example, in neovim editor, the system selects the text (it considers one click as a double click)

**Comment by linuxmobile** [comment]
> I'v installed it on my laptop and the problem is that if I try to make a mouse click, for example, in neovim editor, the system selects the text (it considers one click as a double click)

I'm not using laptop. Sorry
