### ISSUE TITLE
Icons of waybar is not showing correctly

### ISSUE THREAD

**Issue by skmishra-code** [linuxmobile/hyprland-dots#43]
I have installed this linux mobile hyprland setup with paru on arch.
But after the installation My waybar icons is not showing correctly.

![1695549853 screensht](https://github.com/linuxmobile/hyprland-dots/assets/135965332/8636bfb0-348c-47a2-bed5-60f130e2fa04)

**Comment by linuxmobile** [comment]
> I have installed this linux mobile hyprland setup with paru on arch. But after the installation My waybar icons is not showing correctly.
> 
> ![1695549853 screensht](https://user-images.githubusercontent.com/135965332/270157620-8636bfb0-348c-47a2-bed5-60f130e2fa04.png)

Do not open an issue that has already been answered. https://github.com/linuxmobile/hyprland-dots/issues/36
