### ISSUE TITLE
Font Not displaying

### ISSUE THREAD

**Issue by sycinue-rdc** [linuxmobile/hyprland-dots#44]
There are some unicode characters in the waybar that are not displaying for me. i did install all the dependecies and follow the instructions but only this unicode characters are not displaying in my system.

1. 󰧞
2. 󰒮
3. 󰐌
4. 󰏥
5. 󰍛
6. 󰻠
7. 󰋊
8. 󰤨
9. 󰤭
10. 󰝟
11. 󰕿
12. 󰖀
13. 󰕾
14. 󰏘
15. 󰈸
16. 󰈋

**Comment by linuxmobile** [comment]
> There are some unicode characters in the waybar that are not displaying for me. i did install all the dependecies and follow the instructions but only this unicode characters are not displaying in my system.

https://github.com/linuxmobile/hyprland-dots/issues/36

**Do not open an issue that has already been answered**
