### ISSUE TITLE
Blur doesn't work.

### ISSUE THREAD

**Issue by TalinTheDev** [linuxmobile/hyprland-dots#46]
How do you get the blur to work like that? I love that effect but can't get it to work.

This is my decoration right now:
```
decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 0
    active_opacity = 1#0.75
    inactive_opacity = 1#0.75

    blur {
        enabled = true
        size = 6 # 1
        passes = 3 # 100
        ignore_opacity = true
        xray = true
        new_optimizations = true
    }

}
```
It doesn't do anything, the windows are still opaque. 

Any help?

Thanks!

**Comment by linuxmobile** [comment]
> How do you get the blur to work like that? I love that effect but can't get it to work.

Ask in hyprland repository. I'm not a support guy.
