### ISSUE TITLE
Missing Hibernate Option in wlogout Config

### ISSUE THREAD

**Issue by H4ruKey** [linuxmobile/hyprland-dots#47]
The "hibernate" option is  missing from the wlogout configuration, resulting in only five out of six available options being defined. And it causes the sixth place to appear blank when using wlogout.

I have edited the "layout" file for wlogout and added "hibernate" :

`{
    "label" : "hibernate",
    "action" : "systemctl hibernate",
    "text" : "Hibernate",
    "keybind" : "h"
}` 

And for the "style.css" file : 

`#hibernate {
    background-image: image(url("./hibernate.png"));
}
#hibernate:focus {
    background-image: image(url("./hibernate-hover.png"));
}`

_I have also added the "hibernate" icon._

**Comment by linuxmobile** [comment]
Can you do a pr?

**Comment by H4ruKey** [comment]
> Can you do a pr?

Sure
