### ISSUE TITLE
weather isn't working

### ISSUE THREAD

**Issue by Zalan2006** [linuxmobile/hyprland-dots#5]
okay, I've read everything, I've looked through it all, but I don't know what's wrong. I am on a new system but for some reason the weather is not working, what could be missing? 
![image](https://user-images.githubusercontent.com/69893196/215354841-215cd6de-69ea-4f79-a980-8b6aea173cdd.png)

**Comment by linuxmobile** [comment]
> okay, I've read everything, I've looked through it all, but I don't know what's wrong. I am on a new system but for some reason the weather is not working, what could be missing? ![image](https://user-images.githubusercontent.com/69893196/215354841-215cd6de-69ea-4f79-a980-8b6aea173cdd.png)

Install python-pip & with pip install request

**Comment by Airmancooma** [comment]
> > okay, I've read everything, I've looked through it all, but I don't know what's wrong. I am on a new system but for some reason the weather is not working, what could be missing? ![image](https://user-images.githubusercontent.com/69893196/215354841-215cd6de-69ea-4f79-a980-8b6aea173cdd.png)
> 
> Install python-pip & with pip install request

And this command where should I run?

**Comment by linuxmobile** [comment]
> > > okay, I've read everything, I've looked through it all, but I don't know what's wrong. I am on a new system but for some reason the weather is not working, what could be missing? ![image](https://user-images.githubusercontent.com/69893196/215354841-215cd6de-69ea-4f79-a980-8b6aea173cdd.png)
> > 
> > 
> > Install python-pip & with pip install request
> 
> And this command where should I run?

Python-pip from your package manager & next to it do pip install request... something like that. Use google

**Comment by Zalan2006** [comment]
> 

ok i knowed this but
![image](https://user-images.githubusercontent.com/69893196/215356932-21fb650c-27a0-4d5e-a3f9-cfebd8eb579b.png)

**Comment by Zalan2006** [comment]
> > > > okay, I've read everything, I've looked through it all, but I don't know what's wrong. I am on a new system but for some reason the weather is not working, what could be missing? ![image](https://user-images.githubusercontent.com/69893196/215354841-215cd6de-69ea-4f79-a980-8b6aea173cdd.png)
> > > 
> > > 
> > > Install python-pip & with pip install request
> > 
> > 
> > And this command where should I run?
> 
> Python-pip from your package manager & next to it do pip install request... something like that. Use google

ok i solved it i ran the .py in terminal and it wrote out what the error was missing "requests" pip3 install requests i downloaded it now cool
