### ISSUE TITLE
Turn Monitor Off

### ISSUE THREAD

**Issue by jrock2004** [linuxmobile/hyprland-dots#7]
Do you have support that that your machine will auto lock and then turn off screen at some point?

**Comment by linuxmobile** [comment]
> Do you have support that that your machine will auto lock and then turn off screen at some point?

I never used those features but you can create a script to do what you want!

& add this if you need

![image](https://user-images.githubusercontent.com/10554636/215858696-c30cf5d8-0cfa-43da-83db-5031dff2f626.png)

**Comment by jrock2004** [comment]
@linuxmobile where is this pulled from?
