### ISSUE TITLE
Rofi - Hard to See

### ISSUE THREAD

**Issue by jrock2004** [linuxmobile/hyprland-dots#8]
Do you have issues seeing Rofi on certain backgrounds?

![image](https://user-images.githubusercontent.com/655716/215914810-fc860700-0853-4dda-aaf6-6aeae73fa531.png)

**Comment by linuxmobile** [comment]
> Do you have issues seeing Rofi on certain backgrounds?
> 
> ![image](https://user-images.githubusercontent.com/655716/215914810-fc860700-0853-4dda-aaf6-6aeae73fa531.png)

I don't have that problem because I don't use websites with a white background. The problem is independent of my dotfiles! Change the background and that's it <3

**Comment by jrock2004** [comment]
So if you have something like slack on the left side of your screen and its not white, I still have that issue
